Repository php-lightning/lnaddress, pull requests merged in 2023-04, with the labels that each got.

#4 Add readme badges
  README.md
Labels: enhancement

#3 Create callback url command
  README.md
  composer.json
  composer.lock
  config/default.php
  index.php
  lnaddress
  phpstan.neon
  src/Console/ConsoleDependencyProvider.php
  src/Console/ConsoleFactory.php
  src/Console/Infrastructure/ConsoleBootstrap.php
  src/Invoice/Domain/CallbackUrl/CallbackUrl.php
  src/Invoice/Domain/CallbackUrl/CallbackUrlInterface.php
  src/Invoice/Domain/LnAddress/FileBaseNameLnAddressGenerator.php
  src/Invoice/Domain/LnAddress/InvoiceGenerator.php
  src/Invoice/Domain/LnAddress/LnAddressGeneratorInterface.php
  src/Invoice/Infrastructure/Command/CallbackUrlCommand.php
  src/Invoice/InvoiceConfig.php
  src/Invoice/InvoiceFacade.php
  src/Invoice/InvoiceFacadeInterface.php
  src/Invoice/InvoiceFactory.php
  src/Lightning.php
  tests/Feature/GetCallbackUrlFeatureTest.php
  tests/Unit/Invoice/Domain/CallbackUrl/CallbackUrlTest.php
  tests/Unit/Invoice/Domain/LnAddress/InvoiceGeneratorTest.php
Labels: refactoring

#5 Add fluent interface for config
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .php-cs-fixer.dist.php
  config/default-prod.php
  config/default.php
  index.php
  phpstan.neon
  phpunit.xml
  src/Config/Backend/BackendConfigInterface.php
  src/Config/Backend/LnBitsBackendConfig.php
  src/Config/BackendsConfig.php
  src/Config/LightningConfig.php
  src/Http/HttpFactory.php
  src/Invoice/Domain/BackendInvoice/BackendInvoiceInterface.php
  src/Invoice/Domain/BackendInvoice/EmptyBackendInvoice.php
  src/Invoice/Domain/BackendInvoice/LnbitsBackendInvoice.php
  src/Invoice/Domain/CallbackUrl/CallbackUrl.php
  src/Invoice/Domain/LnAddress/InvoiceGenerator.php
  src/Invoice/Domain/Transfer/SendableRange.php
  src/Invoice/InvoiceConfig.php
  src/Invoice/InvoiceFacade.php
  src/Invoice/InvoiceFacadeInterface.php
  src/Invoice/InvoiceFactory.php
  tests/Feature/GetCallbackUrlFeature.php
  tests/Unit/Invoice/Domain/CallbackUrl/CallbackUrlTest.php
  tests/Unit/Invoice/Domain/LnAddress/InvoiceGeneratorTest.php
Labels: enhancement

#6 Refactor api module
  config/default-prod.php
  index.php
  src/Config/LightningConfig.php
  src/Http/Domain/FakeHttpApi.php
  src/Http/Domain/HttpApi.php
  src/Http/Domain/HttpApiInterface.php
  src/Http/Domain/HttpClientInterface.php
  src/Http/HttpDependencyProvider.php
  src/Http/HttpFacade.php
  src/Http/HttpFacadeInterface.php
  src/Http/HttpFactory.php
  src/Http/Infrastructure/FakeHttpClient.php
  src/Http/Infrastructure/RealHttpApi.php
  src/Http/Infrastructure/SymfonyHttpClient.php
  src/Invoice/Domain/BackendInvoice/LnbitsBackendInvoice.php
  src/Invoice/Domain/CallbackUrl/CallbackUrl.php
  src/Invoice/Domain/CallbackUrl/CallbackUrlInterface.php
  src/Invoice/Domain/LnAddress/InvoiceGenerator.php
  src/Invoice/InvoiceFacade.php
  src/Invoice/InvoiceFacadeInterface.php
  src/Invoice/InvoiceFactory.php
  tests/Unit/Invoice/Domain/CallbackUrl/CallbackUrlTest.php
  tests/Unit/Invoice/Domain/LnAddress/InvoiceGeneratorTest.php
Labels: refactoring

#7 Update readme installation
  README.md
  composer.json
  index.php
Labels: documentation

#9 Rename project name from lightning-address to lnaddress
  README.md
  composer.json
  composer.lock
Labels: enhancement

#11 Create VO SendableRange
  lightning-config.php
  phpstan.neon
  src/Config/LightningConfig.php
  src/Invoice/Domain/CallbackUrl/CallbackUrl.php
  src/Invoice/Domain/LnAddress/InvoiceGenerator.php
  src/Invoice/InvoiceConfig.php
  src/Shared/Value/SendableRange.php
  tests/Feature/GetCallbackUrlFeature.php
  tests/Feature/LightningFeature.php
  tests/Unit/Config/LightningConfigTest.php
  tests/Unit/Invoice/Domain/CallbackUrl/CallbackUrlTest.php
  tests/Unit/Invoice/Domain/LnAddress/InvoiceGeneratorTest.php
Labels: enhancement

#12 Get callback-url in index.php when no GET amount
  public/index.php
  src/Lightning.php
  tests/Feature/LightningFeature.php
Labels: enhancement

#13 Rename lightning-config.php to lightning-config.dist.php
  .github/workflows/ci.yml
  .gitignore
  lightning-config.dist.php
  src/Lightning.php
Labels: enhancement

#14 Remove bin/lnaddress script command
  bin/lnaddress
  composer.json
  composer.lock
  src/Console/ConsoleDependencyProvider.php
  src/Console/ConsoleFactory.php
  src/Console/Infrastructure/ConsoleBootstrap.php
  src/Invoice/Infrastructure/Command/CallbackUrlCommand.php
  tests/Feature/GetCallbackUrlFeature.php
Labels: refactoring

#16 Create BackendInvoiceResponse
  src/Invoice/Domain/BackendInvoice/BackendInvoiceInterface.php
  src/Invoice/Domain/BackendInvoice/EmptyBackendInvoice.php
  src/Invoice/Domain/BackendInvoice/LnbitsBackendInvoice.php
  src/Invoice/Domain/LnAddress/InvoiceGenerator.php
  src/Shared/Transfer/BackendInvoiceResponse.php
  tests/Feature/LightningFeature.php
  tests/Unit/Invoice/Domain/BackendInvoice/LnbitsBackendInvoiceTest.php
  tests/Unit/Invoice/Domain/CallbackUrl/CallbackUrlTest.php
  tests/Unit/Invoice/Domain/LnAddress/InvoiceGeneratorTest.php
Labels: refactoring

#18 Use symfony controllers for the endpoint
  .gitignore
  README.md
  bin/console
  composer.json
  composer.lock
  config/bundles.php
  config/preload.php
  config/routes.php
  config/services.php
  lightning-config.dist.php
  phpstan.neon
  public/index.php
  src/Config/Backend/BackendConfigInterface.php
  src/Config/Backend/LnBitsBackendConfig.php
  src/Config/BackendsConfig.php
  src/Config/LightningConfig.php
  src/Invoice/Domain/CallbackUrl/CallbackUrl.php
  src/Invoice/Domain/CallbackUrl/CallbackUrlInterface.php
  src/Invoice/Domain/CallbackUrl/LnAddressGenerator.php
  src/Invoice/Domain/CallbackUrl/LnAddressGeneratorInterface.php
  src/Invoice/Infrastructure/Controller/InvoiceController.php
  src/Invoice/Infrastructure/Http/HttpApi.php
  src/Invoice/InvoiceConfig.php
  src/Invoice/InvoiceFacade.php
  src/Invoice/InvoiceFacadeInterface.php
  src/Invoice/InvoiceFactory.php
  src/Kernel.php
  src/Lightning.php
  tests/Feature/InvoiceFacadeTest.php
  tests/Unit/Config/LightningConfigTest.php
  tests/Unit/Invoice/Domain/CallbackUrl/CallbackUrlTest.php
  tests/bootstrap.php
Labels: enhancement

#19 Remove Symfony and create custom Router
  .gitignore
  bin/console
  composer.json
  composer.lock
  config/bundles.php
  config/preload.php
  config/routes.php
  config/services.php
  public/index.php
  src/Invoice/Infrastructure/Controller/InvoiceController.php
  src/Kernel.php
  src/Router/Router.php
  tests/Unit/Router/RouterTest.php
Labels: enhancement

#20 Use callable controllers
  public/index.php
  src/Invoice/Infrastructure/Controller/InvoiceController.php
  src/Router/Request.php
  src/Router/Router.php
Labels: refactoring

#21 Allow add backends as json
  lightning-config.dist.php
  src/Config/Backend/LnBitsBackendConfig.php
  src/Config/LightningConfig.php
  tests/Feature/InvoiceFacadeTest.php
  tests/Feature/nostr.json
  tests/Unit/Config/LightningConfigTest.php
Labels: enhancement
